language: node_js

node_js:
  - "6.11.1"

cache:
  directories:
    - node_modules

install: 
  - npm install
  - typings install

script:
  - gulp

after_success:
  - npm run semantic-release

sudo: required