language: node_js

node_js:
  - "5"

cache:
  directories:
    - node_modules

services:
  - mongodb

install: 
  - npm install
  - typings install

script:
  - npm run-script test

after_success:
  - npm run semantic-release
  
sudo: required
